### ISSUE TITLE
RUM crashing Next.js App: Cannot read properties of undefined (reading 'POINTER_UP')

### ISSUE THREAD

**Issue by leoyu037** [DataDog/browser-sdk#2557]
**Describe the bug**
Followed the [official docs](https://docs.datadoghq.com/real_user_monitoring/guide/monitor-your-nextjs-app-with-rum/) for adding RUM to nextjs and put the init in `_app.tsx`. This works fine when running on my Macbook M1 but crashes when running inside a docker container:

![Screenshot 2024-01-08 at 2 05 01 PM](https://github.com/DataDog/browser-sdk/assets/1095664/63f1808d-119d-4c03-b83a-a748f15e04ee)

```bash
  TypeError: Cannot read properties of undefined (reading 'POINTER_UP')
      at Object.<anonymous> (/app/node_modules/@datadog/browser-rum/cjs/domain/record/observers/mouseInteractionObserver.js:22:33)
      at Module._compile (node:internal/modules/cjs/loader:1198:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
      at Module.load (node:internal/modules/cjs/loader:1076:32)
      at Function.Module._load (node:internal/modules/cjs/loader:911:12)
      at Module.require (node:internal/modules/cjs/loader:1100:19)
      at require (node:internal/modules/cjs/helpers:119:18)
      at Object.<anonymous> (/app/node_modules/@datadog/browser-rum/cjs/domain/record/observers/observers.js:6:34)
      at Module._compile (node:internal/modules/cjs/loader:1198:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
```

Reproducible with: 
- browser-rum: 5.6.0 and 4.46.0
- next: 13.1.5
- base image: `node:16.20-alpine3.16` and `node:16.20-bookworm-slim`

**Comment by leoyu037** [comment]
It sounds like `DOM_EVENT` is undefined at runtime or something: https://github.com/DataDog/browser-sdk/blob/main/packages/core/src/browser/addEventListener.ts#L10

**Comment by bcaudan** [comment]
Hi @leoyu037,

From the stacktrace:
```
TypeError: Cannot read properties of undefined (reading 'POINTER_UP')
    at Object.<anonymous> (/app/node_modules/@datadog/browser-rum/cjs/domain/record/observers/mouseInteractionObserver.js:22:33)
``` 
It seems that from `browser-rum` `mouseInteractionObserver.js`, you can't access `browser-core` `DOM_EVENT`.
You should probably look into how the dependencies are resolved in your setup and if there is anything that could prevent `browser-rum` code to import something from `browser-core`.

**Comment by leoyu037** [comment]
Hey thanks for the reply, let me investigate -- something that I'm just realizing now is that I'm using dev mode when testing on my local machine, which doesn't use the production build path.

**Comment by leoyu037** [comment]
I'm closing this for now, staying on 4.46.0 seems to be working
