### ISSUE TITLE
🙏 Error thrown as console instead of source

### ISSUE THREAD

**Issue by jamesmosier** [DataDog/browser-sdk#2675]
**What are you trying to achieve and what is your issue? Please describe.**

I am using the latest `@datadog/browser-rum` package (`5.13.0`) and I am seeing some unexpected (?) behavior with how exceptions are being thrown. 

As pictured, when an exception is thrown in my application it looks like the `consoleObserable` from the browser-rum package is picking up the error and reporting it as a `source: 'console'` instead of `source: 'source'`. The reason I believe this to be potentially incorrect is because when I inspect the location of where the second error in the screenshot is thrown, it is a throwing an exception.

![CleanShot 2024-03-29 at 09 02 11@2x](https://github.com/DataDog/browser-sdk/assets/2854919/7670603f-4b72-4421-b723-2e731a90d13b)

If I put a breakpoint on the `throw` from `react-dom.production.min.js:127` (the second error), browser-rum has already output the error as a console error before the exception is thrown. 

Below is the payload sent to the Datadog API:

```json
"error": {
    "id": "1459234b-aab7-4466-a65c-1d2fea381d0b",
    "message": "TypeError: Cannot read properties of undefined (reading 'map')",
    "source": "console",
    "stack": "TypeError: Cannot read properties of undefined (reading 'map')\n  at ConnectedApps @ https://iorwefkcdls.cloudfront.net/gen/js/entrypoint-dashboard.ac0028c2620acb385fa7.chunk-ep.js:1:13459\n  at Xh @ https://iorwefkcdls.cloudfront.net/gen/js/entrypoint-dashboard.287af57947304e046ca0.js:987:65430\n  at ep @ https://iorwefkcdls.cloudfront.net/gen/js/entrypoint-dashboard.287af57947304e046ca0.js:987:129113\n  at Vk @ https://iorwefkcdls.cloudfront.net/gen/js/entrypoint-dashboard.287af57947304e046ca0.js:987:107090\n  at <anonymous> @ https://iorwefkcdls.cloudfront.net/gen/js/entrypoint-dashboard.287af57947304e046ca0.js:987:106950\n  at Jk @ https://iorwefkcdls.cloudfront.net/gen/js/entrypoint-dashboard.287af57947304e046ca0.js:987:106957\n  at Ok @ https://iorwefkcdls.cloudfront.net/gen/js/entrypoint-dashboard.287af57947304e046ca0.js:987:103434\n  at Fk @ https://iorwefkcdls.cloudfront.net/gen/js/entrypoint-dashboard.287af57947304e046ca0.js:987:103868\n  at jg @ https://iorwefkcdls.cloudfront.net/gen/js/entrypoint-dashboard.287af57947304e046ca0.js:987:47639\n  at <anonymous> @ https://iorwefkcdls.cloudfront.net/gen/js/entrypoint-dashboard.287af57947304e046ca0.js:987:101137",
    "handling_stack": "Error: \n  at Mi @ https://iorwefkcdls.cloudfront.net/gen/js/entrypoint-dashboard.287af57947304e046ca0.js:987:75033\n  at Oi.eo.callback @ https://iorwefkcdls.cloudfront.net/gen/js/entrypoint-dashboard.287af57947304e046ca0.js:987:75272\n  at ih @ https://iorwefkcdls.cloudfront.net/gen/js/entrypoint-dashboard.287af57947304e046ca0.js:987:54824\n  at lk @ https://iorwefkcdls.cloudfront.net/gen/js/entrypoint-dashboard.287af57947304e046ca0.js:987:98249\n  at jk @ https://iorwefkcdls.cloudfront.net/gen/js/entrypoint-dashboard.287af57947304e046ca0.js:987:120042\n  at <anonymous> @ https://iorwefkcdls.cloudfront.net/gen/js/entrypoint-dashboard.287af57947304e046ca0.js:987:120056\n  at Qk @ https://iorwefkcdls.cloudfront.net/gen/js/entrypoint-dashboard.287af57947304e046ca0.js:987:120607\n  at Fk @ https://iorwefkcdls.cloudfront.net/gen/js/entrypoint-dashboard.287af57947304e046ca0.js:987:104029",
    "handling": "handled",
    "source_type": "browser"
  }
```

**Describe the solution you'd like**
I'd like exceptions that are thrown from source code to be treated as a source error. Is there a way to ensure thrown exceptions are treated as "source" errors?

**Describe alternatives you've considered**
🤷

**Comment by jamesmosier** [comment]
That makes sense, thanks for the quick response @bcaudan! Seems like React is catching these and even though it appear to re-throw them (where I looked at least) it must be console.error-ing them somewhere. I'll investigate further.

In the meantime, I think using an `ErrorBoundary` and manually sending to Datadog might be my best bet.
