### ISSUE TITLE
🙏 Testing `beforeSend` in Jest

### ISSUE THREAD

**Issue by sfc-gh-spanferov** [DataDog/browser-sdk#3109]
**What are you trying to achieve and what is your issue? Please describe.**
We have a pretty complicated logic in `beforeSend`, so I'm trying to write an end-to-end test which would:

* initialize the DataDog RUM SDK
* invoke `addError`
* intercept a before send callback and check our custom logic

However, no matter what I do I cannot force DataDog RUM to actually invoke the `beforeSend()` in the Jest environment.

```typescript
const DD_SERVICE_NAME = 'snowsight';
const DD_SITE = 'datadoghq.com';

Object.defineProperty(window, 'location', {
  value: new URL('https://app.snowflake.com/jest'),
  configurable: true,
});

datadogRum.init({
  applicationId: 'test',
  clientToken: 'test',
  site: DD_SITE,
  service: DD_SERVICE_NAME,
  version: '0.0.1',
  allowUntrustedEvents: true,
  beforeSend: (event: RumEvent) => {
    throw new Error("SHOULD THROW"); // never called
    return false;
  },
});

datadogRum.setUser({
  id: 'test',
  email: 'test@snowflake.com',
});

describe('ErrorBoundary', function () {

  beforeAll(async () => {
    await new Promise((ready) =>
      datadogRum.onReady(() => {
        datadogRum.startView('/test');
        datadogRum.setGlobalContext({});
        console.log('ready');
        ready();
      }),
    );
  });

 it('works', async function () {
    datadogRum.addError(new Error('Test'));
  }, 1000);
```

**Describe the solution you'd like**
I would like some support to see how this can be achieved

**Comment by sfc-gh-spanferov** [comment]
```
TypeError: Cannot read properties of undefined (reading 'navigationStart')
        at getNavigationStart (/Users/spanferov/projects/browser-sdk/packages/core/src/tools/utils/timeUtils.ts:109:42)
        at clocksOrigin (/Users/spanferov/projects/browser-sdk/packages/core/src/tools/utils/timeUtils.ts:67:52)
        at startSessionManager (/Users/spanferov/projects/browser-sdk/packages/core/src/domain/session/sessionManager.ts:66:52)
        at startRumSessionManager (/Users/spanferov/projects/browser-sdk/packages/rum-core/src/domain/rumSessionManager.ts:45:26)
        at startRumImpl (/Users/spanferov/projects/browser-sdk/packages/rum-core/src/boot/startRum.ts:122:5)
        at doStartRum (/Users/spanferov/projects/browser-sdk/packages/rum-core/src/boot/rumPublicApi.ts:395:30)
        at tryStartRum (/Users/spanferov/projects/browser-sdk/packages/rum-core/src/boot/preStartRum.ts:79:28)
        at doInit (/Users/spanferov/projects/browser-sdk/packages/rum-core/src/boot/preStartRum.ts:132:5)
        at Object.init (/Users/spanferov/projects/browser-sdk/packages/rum-core/src/boot/preStartRum.ts:167:9)
        at Object.apply (/Users/spanferov/projects/browser-sdk/packages/rum-core/src/boot/rumPublicApi.ts:436:16)
        at callMonitored (/Users/spanferov/projects/browser-sdk/packages/core/src/tools/monitor.ts:51:15)
        at Object.init (/Users/spanferov/projects/browser-sdk/packages/core/src/tools/monitor.ts:34:12)

```

I've patched the DD SDK and this is the error I managed to get out of it. It would be nice to propagate those errors somehow, maybe on `onReady` callback

**Comment by sfc-gh-spanferov** [comment]
For people who will try to do this after me, here is the solution:

```
Object.defineProperties(performance, {
  timing: {
    value: {
      navigationStart: Date.now(),
    },
    writable: true,
  },
});

```
